apiVersion: v1
kind: Namespace
metadata:
  name: taskapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: taskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: taskapp-backend:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "True"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: taskapp
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
