apiVersion: batch/v1
kind: Job
metadata:
  name: selenium-e2e-tests
  namespace: taskapp
spec:
  template:
    spec:
      initContainers:
      - name: selenium-tests
        image: taskapp-selenium:v1
        imagePullPolicy: Never
        command: ["sh", "-c"]
        args:
          - |
            python3 e2e_tests.py
            allure generate /tmp/allure-results -o /allure-report --clean
            cp -r /allure-report/* /shared/
        volumeMounts:
        - name: shared-report
          mountPath: /shared
      containers:
      - name: report-server
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-report
          mountPath: /usr/share/nginx/html
      volumes:
      - name: shared-report
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 1
